TrajectoryPlannerROS:
  odom_topic: odom
    
  max_vel_x: 0.1
  min_vel_x: 0.01
  max_vel_theta: 1.0   # 0.1 rad/sec = 5.7 degree/sec
  min_in_place_vel_theta: 0.02
  
  acc_lim_theta: 0.05
  acc_lim_x: 0.05
  acc_lim_y: 0.05
  
  holonomic_robot: false

  # goal tolerance parameters
  yaw_goal_tolerance: 0.4         # 0.1 means 5.7 degrees
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false