TrajectoryPlannerROS:
  odom_topic: odom
    
  max_vel_x: 0.18
  min_vel_x: 0.01
  max_rotational_vel: 1.5   # 0.1 rad/sec = 5.7 degree/sec
  min_in_place_rotational_vel: 0.02
  
  acc_lim_th: 0.3
  acc_lim_x: 0.05
  acc_lim_y: 0.05
  
  holonomic_robot: false

  # goal tolerance parameters
  yaw_goal_tolerance: 0.4         # 0.1 means 5.7 degrees
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false