TrajectoryPlannerROS:
    max_vel_x: 0.18
    min_vel_x: 0.01
    max_vel_theta: 2.0
    min_in_place_vel_theta: 0.04
  
    acc_lim_theta: 1.2
    acc_lim_x: 1.5
    acc_lim_y: 1.5
  
    holonomic_robot: false