obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.08, -0.15], [-0.08, 0.05], [0.08, 0,05], [0.08, -0.15]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

